export interface Cocktail {
  drink: string;
  person: string;
  ingredients: string[];
  classicExperimental: number;
  lightSpiritForward: number;
  spiritIntensity: number;
  complexity: number;
  fruitiness: number;
  familiarity: number;
  richness: number;
}

export const COCKTAILS: Cocktail[] = [
  {
    drink: 'Bayle',
    person: 'Agnes',
    ingredients: ['lemon', 'gin', 'passionfruit', 'lime', 'bitters'],
    classicExperimental: 0.55,
    lightSpiritForward: -0.35,
    spiritIntensity: 0.55,
    complexity: 0.7,
    fruitiness: 0.9,
    familiarity: 0.45,
    richness: 0.25,
  },
  {
    drink: 'Margarita',
    person: 'Agnes',
    ingredients: ['tequila', 'agave', 'blackberry', 'orange bitters', 'simple syrup'],
    classicExperimental: -0.1,
    lightSpiritForward: -0.15,
    spiritIntensity: 0.65,
    complexity: 0.5,
    fruitiness: 0.75,
    familiarity: 0.9,
    richness: 0.3,
  },
  {
    drink: 'Gin Basil Smash',
    person: 'Agnes',
    ingredients: ['gin', 'lemon', 'simple syrup', 'basil'],
    classicExperimental: -0.2,
    lightSpiritForward: -0.45,
    spiritIntensity: 0.45,
    complexity: 0.55,
    fruitiness: 0.6,
    familiarity: 0.7,
    richness: 0.15,
  },
  {
    drink: 'Tamarind Type Shit Daiquiri',
    person: 'Agnes',
    ingredients: ['gin', 'basil'],
    classicExperimental: 0.85,
    lightSpiritForward: 0.1,
    spiritIntensity: 0.6,
    complexity: 0.85,
    fruitiness: 0.5,
    familiarity: 0.2,
    richness: 0.2,
  },
  {
    drink: 'Bachata',
    person: 'Andy',
    ingredients: ['white rum', 'oat milk', 'amaretto', 'cinnamon', 'milk'],
    classicExperimental: 0.95,
    lightSpiritForward: 0.15,
    spiritIntensity: 0.5,
    complexity: 0.75,
    fruitiness: 0.2,
    familiarity: 0.35,
    richness: 0.95,
  },
  {
    drink: 'Hueaw',
    person: 'Andy',
    ingredients: ['whiskey', 'lemon', 'orange', 'bitters', 'oolong'],
    classicExperimental: 0.6,
    lightSpiritForward: 0.65,
    spiritIntensity: 0.8,
    complexity: 0.7,
    fruitiness: 0.35,
    familiarity: 0.4,
    richness: 0.65,
  },
  {
    drink: 'Yuzu Drink',
    person: 'Drew',
    ingredients: ['yuzu', 'midori', 'mint', 'gin', 'vodka', 'soda water'],
    classicExperimental: 0.9,
    lightSpiritForward: -0.7,
    spiritIntensity: 0.45,
    complexity: 0.9,
    fruitiness: 0.95,
    familiarity: 0.25,
    richness: 0.05,
  },
  {
    drink: 'Moscow Mule',
    person: 'Erika',
    ingredients: ['vodka', 'ginger beer', 'lime', 'basil'],
    classicExperimental: -0.45,
    lightSpiritForward: -0.6,
    spiritIntensity: 0.4,
    complexity: 0.35,
    fruitiness: 0.65,
    familiarity: 0.95,
    richness: 0.1,
  },
  {
    drink: 'Horchata',
    person: 'Erika',
    ingredients: ['cinnamon', 'milk'],
    classicExperimental: 0.4,
    lightSpiritForward: -0.95,
    spiritIntensity: 0.05,
    complexity: 0.2,
    fruitiness: 0.1,
    familiarity: 0.85,
    richness: 1,
  },
  {
    drink: 'Penicillin',
    person: 'Jasper',
    ingredients: ['scotch', 'ginger', 'lemon', 'honey'],
    classicExperimental: -0.15,
    lightSpiritForward: 0.55,
    spiritIntensity: 0.85,
    complexity: 0.75,
    fruitiness: 0.35,
    familiarity: 0.75,
    richness: 0.6,
  },
  {
    drink: 'Espresso Martini',
    person: 'Jasper',
    ingredients: ['vodka', 'coffee', 'white rum'],
    classicExperimental: 0.1,
    lightSpiritForward: 0.35,
    spiritIntensity: 0.75,
    complexity: 0.55,
    fruitiness: 0.15,
    familiarity: 0.95,
    richness: 0.7,
  },
  {
    drink: 'Mezcal Reposado',
    person: 'Marco',
    ingredients: ['mezcal', 'reposado'],
    classicExperimental: -0.3,
    lightSpiritForward: 0.95,
    spiritIntensity: 0.95,
    complexity: 0.4,
    fruitiness: 0.05,
    familiarity: 0.7,
    richness: 0.8,
  },
  {
    drink: 'Manhattan',
    person: 'Marco',
    ingredients: ['bourbon', 'lemon'],
    classicExperimental: -0.85,
    lightSpiritForward: 0.9,
    spiritIntensity: 0.95,
    complexity: 0.65,
    fruitiness: 0.2,
    familiarity: 0.9,
    richness: 0.7,
  },
  {
    drink: 'Old Fashioned',
    person: 'Marco',
    ingredients: ['whiskey', 'orange', 'bitters'],
    classicExperimental: -1,
    lightSpiritForward: 1,
    spiritIntensity: 1,
    complexity: 0.5,
    fruitiness: 0.15,
    familiarity: 1,
    richness: 0.75,
  },
  {
    drink: 'Daiquiri',
    person: 'Marco',
    ingredients: ['gin', 'coconut', 'simple syrup'],
    classicExperimental: 0.35,
    lightSpiritForward: -0.1,
    spiritIntensity: 0.5,
    complexity: 0.45,
    fruitiness: 0.55,
    familiarity: 0.75,
    richness: 0.25,
  },
  {
    drink: 'Sazerac',
    person: 'Marco',
    ingredients: ['bourbon', 'bitters', 'orange'],
    classicExperimental: -0.95,
    lightSpiritForward: 0.98,
    spiritIntensity: 1,
    complexity: 0.7,
    fruitiness: 0.1,
    familiarity: 0.85,
    richness: 0.85,
  },
  {
    drink: "Matty's Sangria",
    person: 'Matty',
    ingredients: ['wine', 'cinnamon', 'soda water', 'orange'],
    classicExperimental: 0.25,
    lightSpiritForward: -0.65,
    spiritIntensity: 0.2,
    complexity: 0.4,
    fruitiness: 0.8,
    familiarity: 0.95,
    richness: 0.2,
  },
  {
    drink: 'Espresso Rum Drink',
    person: 'Matty',
    ingredients: ['bacardi white/black rum', 'almond syrup', 'angelico', 'espresso shot'],
    classicExperimental: 0.75,
    lightSpiritForward: 0.7,
    spiritIntensity: 0.9,
    complexity: 0.85,
    fruitiness: 0.1,
    familiarity: 0.3,
    richness: 0.9,
  },
  {
    drink: 'Ube Infused Bourbon Drink',
    person: 'Matty',
    ingredients: ['ube-infused bourbon', 'crème de cacao', 'vodka'],
    classicExperimental: 1,
    lightSpiritForward: 0.8,
    spiritIntensity: 0.9,
    complexity: 1,
    fruitiness: 0.2,
    familiarity: 0.1,
    richness: 1,
  },
  {
    drink: 'Penicillin',
    person: 'Sam',
    ingredients: ['scotch', 'ginger', 'lemon', 'honey'],
    classicExperimental: -0.15,
    lightSpiritForward: 0.55,
    spiritIntensity: 0.85,
    complexity: 0.75,
    fruitiness: 0.35,
    familiarity: 0.75,
    richness: 0.6,
  },
  {
    drink: "Sam's Sangria",
    person: 'Sam',
    ingredients: ['wine', 'pineapple', 'lemon', 'orange bitters'],
    classicExperimental: 0.45,
    lightSpiritForward: -0.55,
    spiritIntensity: 0.25,
    complexity: 0.55,
    fruitiness: 0.95,
    familiarity: 0.8,
    richness: 0.15,
  },
  {
    drink: 'Flora Dora',
    person: 'Sam',
    ingredients: ['ginger', 'gin', 'floral notes'],
    classicExperimental: 0.3,
    lightSpiritForward: -0.5,
    spiritIntensity: 0.4,
    complexity: 0.6,
    fruitiness: 0.5,
    familiarity: 0.5,
    richness: 0.1,
  },
];
